### ISSUE TITLE
Update description link

### ISSUE THREAD

**Issue by evsprn** [exercism/common-lisp#174] opened 2017-09-01 14:17 UTC
http://exercism.io/languages/lisp is the actual URL.

**Comment by verdammelt** [comment] 2017-09-01 14:28
Good catch!

@kytrinyx I don't seem to have edit ability on this repository so I can't fix the description myself. Can you either give me edit ability on this repo or just quickly change the link the language?

-OR-

Should the link actually be `http://exercism.io/languages/common-lisp` and so the problem is in `exercism.io`?

**Comment by kytrinyx** [comment] 2017-09-01 17:33
How do you not have edit ability? Let me add you to the team.

That said, I think the problem is in exercism.io - I'll fix that now.

**Comment by kytrinyx** [comment] 2017-09-01 17:34
@verdammelt You totally have edit ability on this repo. I don't understand why you'd be told that you are not!

**Comment by kytrinyx** [comment] 2017-09-01 17:42
OK, deploying that fix now.

**Comment by verdammelt** [comment] 2017-09-01 18:22
Thanks @kytrinyx. The reason I said I don't seem to have edit on this repo is because GitHub is not giving me an 'EDIT' button next to the description.

**Comment by verdammelt** [comment] 2017-09-01 18:23
Just confirmed that the common-lisp link works - closing this issue. 

Thanks again @kytrinyx

**Closed by verdammelt** 2017-09-01 18:23 UTC
