### ISSUE TITLE
Leslie's Lengthy Lists   peeking-at-the-list test

### ISSUE THREAD

**Issue by michael-776** [exercism/common-lisp#484] opened 2021-09-05 19:41 UTC
Unless I'm seriously missing something here, the 23rd item in the list is "birthday-candles" -- but the test says it's supposed to be "cupcakes"

May be better to do the tests like this:
(is (equal (nth 0 shopping-list) (first-thing shopping-list)))
        (is (equal (nth 1 shopping-list) (second-thing shopping-list)))
        (is (equal (nth 2 shopping-list) (third-thing shopping-list)))
        (is (equal (nth 22 shopping-list) (twenty-third-thing shopping-list)))

**Comment by verdammelt** [comment] 2021-09-06 00:33
Ah, i see what the problem is... when i wrote it my brain immediately connected `twenty-third-thing` with `(nth 23..)` which is of course incorrect "twenty-third thing" would be `(nth 24...)` 

Thanks for brining this up and it will be fixed shortly.

**Closed** 2021-09-06 01:28 UTC
Labels: x:status/claimed
